GPUS: (0,)
WORKERS: 4
PRINT_FREQ: 50
NUM_CLASS: 3
RESULT_PATH: './experiments'
IMAGE_RESIZE:
  - 800
  - 800
IMAGE_SIZE:
  - 1600
  - 1200
MODEL:
  NAME: 'vgg'
TRAIN:
  BATCH_SIZE_PER_GPU: 64
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 500
  EARLY_STOP: 10
  OPTIMIZER: 'adam'
  LR: 0.0001
  WD: 0.0
  LR_STEP: [25, 40]
  MOMENTUM: 0.0
  NESTEROV: false
TEST:
  BATCH_SIZE_PER_GPU: 8