GPUS: (0,)
WORKERS: 15
PRINT_FREQ: 50
NUM_CLASS: 7
RESULT_PATH: './experiments'
IMAGE_RESIZE:
  - 300
  - 300
IMAGE_SIZE:
  - 1600
  - 1200
MODEL:
  NAME: 'inceptionv3'
TRAIN:
  BATCH_SIZE_PER_GPU: 50
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 300
  EARLY_STOP: 30
  OPTIMIZER: 'adam'
  LR: 0.00001
  WD: 0.0
  LR_STEP: [30, 50]
  MOMENTUM: 0.0
  NESTEROV: false
TEST:
  BATCH_SIZE_PER_GPU: 8